# Store days of the week and months of the years in tuples
days = ("Monday", "Tuesday", "Wednessday", "Thursday", "Friday")
months = ("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")
name = input("Enter the student's name:")
gender = input("Enter gender:")
course_track = input("Enter course track:")
month_number = int(input("Enter current month number (1-12):"))
day_number = int(input("Enter current day number (1-7):"))
print("\nAttendance Record")
print(f"Name:\t\t{name}")
print(f"Gender:\t\t{gender}")
print(f"Course Track:\t{course_track}")
print(f"Month Number:\t{month_number -1}")
print(f"Day Number:\t{day_number -1}")